2017-08-25 17:52:43 ERROR Logging:31 - Error Log: Test execution has Failed
2017-08-25 18:14:31 INFO  Logging:15 - Info log: Test execution succeeded
java.lang.Exception: Info log: Test execution succeeded
	at loggers.Logging.brokenInfoMethod(Logging.java:39)
	at loggers.Logging.infoLogger(Logging.java:13)
	at listeners.TestNGListeners.onFinish(TestNGListeners.java:47)
	at org.testng.TestRunner.fireEvent(TestRunner.java:1187)
	at org.testng.TestRunner.afterRun(TestRunner.java:976)
	at org.testng.TestRunner.run(TestRunner.java:606)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
